# Generated by Django 5.1.1 on 2025-02-25 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/media/')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BibleQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('dates_posted', models.DateField(help_text='Date when this quote should be displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['dates_posted'],
            },
        ),
        migrations.CreateModel(
            name='TemplateForBibleQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('template_file', models.ImageField(upload_to='media_templates/')),
                ('dates_posted', models.DateField(help_text='Date when this template should be displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['dates_posted'],
            },
        ),
        migrations.CreateModel(
            name='ProgramDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Enter the title of the upload(e.g, 'Sunday Service Banner')", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of the media', null=True)),
                ('image', models.ImageField(help_text='Upload an image, video or document', upload_to='uploads/media/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the file', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media Upload',
                'verbose_name_plural': 'Media Uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DisplayBibleQuotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('dates_posted', models.DateField(help_text='Date when this annoucement should be displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bible_quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.biblequote')),
                ('media_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.templateforbiblequote')),
            ],
            options={
                'ordering': ['dates_posted'],
            },
        ),
    ]
