# Generated by Django 5.1.3 on 2025-02-12 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginRecord',
        ),
    ]
